DEFAULT_ADDRESS_OBJECTS = ['X0 IP', 'X1 IP', 'X2 IP', 'X3 IP', 'X4 IP', 'X5 IP', 'X6 IP', 'X7 IP', 'X8 IP', 'X9 IP',
                           'X10 IP', 'X11 IP',
                           'X12 IP', 'X13 IP', 'X14 IP', 'X15 IP', 'X16 IP', 'X17 IP', 'X18 IP', 'X19 IP', 'LAN IP',
                           'WAN IP', 'U0 IP',
                           'U1 IP', 'MGMT IP', 'X0 Subnet', 'X1 Subnet', 'X2 Subnet', 'X3 Subnet', 'X4 Subnet',
                           'X5 Subnet', 'X6 Subnet',
                           'X7 Subnet', 'X8 Subnet', 'X9 Subnet', 'X10 Subnet', 'X11 Subnet', 'X12 Subnet',
                           'X13 Subnet', 'X14 Subnet',
                           'X15 Subnet', 'X16 Subnet', 'X17 Subnet', 'X18 Subnet', 'X19 Subnet', 'LAN Subnet',
                           'WAN Subnet', 'U0 Subnet',
                           'U1 Subnet', 'MGMT Subnet', 'X0 IPv6 Link-Local Address', 'X1 IPv6 Link-Local Address',
                           'X2 IPv6 Link-Local Address', 'X3 IPv6 Link-Local Address', 'X4 IPv6 Link-Local Address',
                           'X5 IPv6 Link-Local Address', 'X6 IPv6 Link-Local Address', 'X7 IPv6 Link-Local Address',
                           'X8 IPv6 Link-Local Address', 'X9 IPv6 Link-Local Address', 'X10 IPv6 Link-Local Address',
                           'X11 IPv6 Link-Local Address', 'X12 IPv6 Link-Local Address', 'X13 IPv6 Link-Local Address',
                           'X14 IPv6 Link-Local Address', 'X15 IPv6 Link-Local Address', 'X16 IPv6 Link-Local Address',
                           'X17 IPv6 Link-Local Address', 'X18 IPv6 Link-Local Address', 'X19 IPv6 Link-Local Address',
                           'LAN IPv6 Link-Local Address', 'WAN IPv6 Link-Local Address', 'U0 IPv6 Link-Local Address',
                           'U1 IPv6 Link-Local Address', 'MGMT IPv6 Link-Local Address',
                           'X0 IPv6 Primary Static Address',
                           'X1 IPv6 Primary Static Address', 'X2 IPv6 Primary Static Address',
                           'X3 IPv6 Primary Static Address',
                           'X4 IPv6 Primary Static Address', 'X5 IPv6 Primary Static Address',
                           'X6 IPv6 Primary Static Address',
                           'X7 IPv6 Primary Static Address', 'X8 IPv6 Primary Static Address',
                           'X9 IPv6 Primary Static Address',
                           'X10 IPv6 Primary Static Address', 'X11 IPv6 Primary Static Address',
                           'X12 IPv6 Primary Static Address',
                           'X13 IPv6 Primary Static Address', 'X14 IPv6 Primary Static Address',
                           'X15 IPv6 Primary Static Address',
                           'X16 IPv6 Primary Static Address', 'X17 IPv6 Primary Static Address',
                           'X18 IPv6 Primary Static Address',
                           'X19 IPv6 Primary Static Address', 'LAN IPv6 Primary Static Address',
                           'WAN IPv6 Primary Static Address',
                           'U0 IPv6 Primary Static Address', 'U1 IPv6 Primary Static Address',
                           'MGMT IPv6 Primary Static Address',
                           'X0 IPv6 Primary Static Address Subnet', 'X1 IPv6 Primary Static Address Subnet',
                           'X2 IPv6 Primary Static Address Subnet', 'X3 IPv6 Primary Static Address Subnet',
                           'X4 IPv6 Primary Static Address Subnet', 'X5 IPv6 Primary Static Address Subnet',
                           'X6 IPv6 Primary Static Address Subnet', 'X7 IPv6 Primary Static Address Subnet',
                           'X8 IPv6 Primary Static Address Subnet', 'X9 IPv6 Primary Static Address Subnet',
                           'X10 IPv6 Primary Static Address Subnet', 'X11 IPv6 Primary Static Address Subnet',
                           'X12 IPv6 Primary Static Address Subnet', 'X13 IPv6 Primary Static Address Subnet',
                           'X14 IPv6 Primary Static Address Subnet', 'X15 IPv6 Primary Static Address Subnet',
                           'X16 IPv6 Primary Static Address Subnet', 'X17 IPv6 Primary Static Address Subnet',
                           'X18 IPv6 Primary Static Address Subnet', 'X19 IPv6 Primary Static Address Subnet',
                           'LAN IPv6 Primary Static Address Subnet', 'WAN IPv6 Primary Static Address Subnet',
                           'U0 IPv6 Primary Static Address Subnet', 'U1 IPv6 Primary Static Address Subnet',
                           'MGMT IPv6 Primary Static Address Subnet', 'X0 IPv6 Primary Dynamic Address',
                           'X1 IPv6 Primary Dynamic Address', 'X2 IPv6 Primary Dynamic Address',
                           'X3 IPv6 Primary Dynamic Address',
                           'X4 IPv6 Primary Dynamic Address', 'X5 IPv6 Primary Dynamic Address',
                           'X6 IPv6 Primary Dynamic Address',
                           'X7 IPv6 Primary Dynamic Address', 'X8 IPv6 Primary Dynamic Address',
                           'X9 IPv6 Primary Dynamic Address',
                           'X10 IPv6 Primary Dynamic Address', 'X11 IPv6 Primary Dynamic Address',
                           'X12 IPv6 Primary Dynamic Address',
                           'X13 IPv6 Primary Dynamic Address', 'X14 IPv6 Primary Dynamic Address',
                           'X15 IPv6 Primary Dynamic Address',
                           'X16 IPv6 Primary Dynamic Address', 'X17 IPv6 Primary Dynamic Address',
                           'X18 IPv6 Primary Dynamic Address',
                           'X19 IPv6 Primary Dynamic Address', 'LAN IPv6 Primary Dynamic Address',
                           'WAN IPv6 Primary Dynamic Address',
                           'U0 IPv6 Primary Dynamic Address', 'U1 IPv6 Primary Dynamic Address',
                           'MGMT IPv6 Primary Dynamic Address',
                           'X0 IPv6 Primary Dynamic Address Subnet', 'X1 IPv6 Primary Dynamic Address Subnet',
                           'X2 IPv6 Primary Dynamic Address Subnet', 'X3 IPv6 Primary Dynamic Address Subnet',
                           'X4 IPv6 Primary Dynamic Address Subnet', 'X5 IPv6 Primary Dynamic Address Subnet',
                           'X6 IPv6 Primary Dynamic Address Subnet', 'X7 IPv6 Primary Dynamic Address Subnet',
                           'X8 IPv6 Primary Dynamic Address Subnet', 'X9 IPv6 Primary Dynamic Address Subnet',
                           'X10 IPv6 Primary Dynamic Address Subnet', 'X11 IPv6 Primary Dynamic Address Subnet',
                           'X12 IPv6 Primary Dynamic Address Subnet', 'X13 IPv6 Primary Dynamic Address Subnet',
                           'X14 IPv6 Primary Dynamic Address Subnet', 'X15 IPv6 Primary Dynamic Address Subnet',
                           'X16 IPv6 Primary Dynamic Address Subnet', 'X17 IPv6 Primary Dynamic Address Subnet',
                           'X18 IPv6 Primary Dynamic Address Subnet', 'X19 IPv6 Primary Dynamic Address Subnet',
                           'LAN IPv6 Primary Dynamic Address Subnet', 'WAN IPv6 Primary Dynamic Address Subnet',
                           'U0 IPv6 Primary Dynamic Address Subnet', 'U1 IPv6 Primary Dynamic Address Subnet',
                           'MGMT IPv6 Primary Dynamic Address Subnet', 'All X0 Management IP', 'All X1 Management IP',
                           'All X2 Management IP', 'All X3 Management IP', 'All X4 Management IP',
                           'All X5 Management IP',
                           'All X6 Management IP', 'All X7 Management IP', 'All X8 Management IP',
                           'All X9 Management IP',
                           'All X10 Management IP', 'All X11 Management IP', 'All X12 Management IP',
                           'All X13 Management IP',
                           'All X14 Management IP', 'All X15 Management IP', 'All X16 Management IP',
                           'All X17 Management IP',
                           'All X18 Management IP', 'All X19 Management IP', 'All LAN Management IP',
                           'All WAN Management IP',
                           'All U0 Management IP', 'All U1 Management IP', 'All MGMT Management IP',
                           'X0 IPv6 Addresses',
                           'X1 IPv6 Addresses', 'X2 IPv6 Addresses', 'X3 IPv6 Addresses', 'X4 IPv6 Addresses',
                           'X5 IPv6 Addresses',
                           'X6 IPv6 Addresses', 'X7 IPv6 Addresses', 'X8 IPv6 Addresses', 'X9 IPv6 Addresses',
                           'X10 IPv6 Addresses',
                           'X11 IPv6 Addresses', 'X12 IPv6 Addresses', 'X13 IPv6 Addresses', 'X14 IPv6 Addresses',
                           'X15 IPv6 Addresses',
                           'X16 IPv6 Addresses', 'X17 IPv6 Addresses', 'X18 IPv6 Addresses', 'X19 IPv6 Addresses',
                           'LAN IPv6 Addresses',
                           'WAN IPv6 Addresses', 'U0 IPv6 Addresses', 'U1 IPv6 Addresses', 'MGMT IPv6 Addresses',
                           'X0 Management IPv6 Addresses', 'X1 Management IPv6 Addresses',
                           'X2 Management IPv6 Addresses',
                           'X3 Management IPv6 Addresses', 'X4 Management IPv6 Addresses',
                           'X5 Management IPv6 Addresses',
                           'X6 Management IPv6 Addresses', 'X7 Management IPv6 Addresses',
                           'X8 Management IPv6 Addresses',
                           'X9 Management IPv6 Addresses', 'X10 Management IPv6 Addresses',
                           'X11 Management IPv6 Addresses',
                           'X12 Management IPv6 Addresses', 'X13 Management IPv6 Addresses',
                           'X14 Management IPv6 Addresses',
                           'X15 Management IPv6 Addresses', 'X16 Management IPv6 Addresses',
                           'X17 Management IPv6 Addresses',
                           'X18 Management IPv6 Addresses', 'X19 Management IPv6 Addresses',
                           'LAN Management IPv6 Addresses',
                           'WAN Management IPv6 Addresses', 'U0 Management IPv6 Addresses',
                           'U1 Management IPv6 Addresses',
                           'MGMT Management IPv6 Addresses',
                           'LAN Subnets', 'WAN Subnets', 'WLAN Subnets', 'DMZ Subnets', 'Firewalled Subnets',
                           'WAN Interface IP',
                           'WLAN Interface IP', 'LAN Interface IP', 'DMZ Interface IP', 'All Interface IP',
                           'WAN Interface IPv6 Addresses', 'WLAN Interface IPv6 Addresses',
                           'LAN Interface IPv6 Addresses',
                           'DMZ Interface IPv6 Addresses', 'All Interface IPv6 Addresses',
                           'LAN IPv6 Subnets', 'WAN IPv6 Subnets', 'WLAN IPv6 Subnets', 'DMZ IPv6 Subnets',
                           'Firewalled IPv6 Subnets', 'LAN Subnets', 'WAN Subnets',
                           'All WAN IP', 'None', 'Firewall SSO Agents', 'Firewall Terminal Services Agents',
                           'McAfee Client AV Enforcement List', 'Excluded from McAfee Client AV Enforcement List',
                           'Capture Client Enforcement List', 'Excluded from Capture Client Enforcement List',
                           'Client CF Enforcement List', 'Excluded from Client CF Enforcement List',
                           'Kaspersky Client AV Enforcement List', 'Excluded from Kaspersky Client AV Enforcement List',
                           'DPI-SSL Enforcement List', 'Excluded from DPI-SSL Enforcement List',
                           'Excluded from Client AV Enforcement List', 'Default Trusted Relay Agent List',
                           'RBL User White List', 'Guest Authentication Server 1', 'Guest Authentication Server 2',
                           'RBL User Black List', 'Node License Exclusion List', 'RADIUS Accounting Clients',
                           'Default Social Login Pass Group',
                           'Public Mail Server Address Group',
                           'SSO 3rd Party API Clients', 'Default Geo-IP and Botnet Exclusion Group',
                           'Social Login Pass Group',
                           'All Authorized Access Points', 'All Rogue Access Points', 'All Rogue Devices',
                           'All SonicPoints',
                           'Default SonicPoint ACL Deny Group', 'Default SonicPoint ACL Allow Group',
                           'Guest Authentication Servers', 'Prefixes from DHCPC6 Delegation',
                           'Default Active WAN IP', 'Default Gateway', 'WAN RemoteAccess Networks', 'Well-Known Pref64',
                           'IPv6 Link-Local Subnet', 'WAN Primary Subnet', 'LAN Primary Subnet',
                           'X1 Default Gateway', 'X1 IPv6 Default Gateway',
                           'Dial-Up Default Gateway', 'WLAN RemoteAccess Networks', 'MGMT Default Gateway',
                           'LAN Primary IP', 'WAN Primary IP', 'W0 Subnet', 'X2 Default Gateway', 'U0 Default Gateway',
                           'User Mail Server Private IP',
                           ]
DEFAULT_DPISSLCLIENT_CFS_CATEGORIES = ['1. Violence/Hate/Racism',
                  '2. Intimate Apparel/Swimsuit',
                  '3. Nudism',
                  '4. Pornography',
                  '5. Weapons',
                  '6. Adult/Mature Content',
                  '7. Cult/Occult',
                  '8. Drugs/Illegal Drugs',
                  '9. Illegal Skills/Questionable Skills',
                  '10. Sex Education',
                  '11. Gambling',
                  '12. Alcohol/Tobacco',
                  '13. Chat/Instant Messaging (IM)',
                  '14. Arts/Entertainment',
                  '15. Business and Economy',
                  '16. Abortion/Advocacy Groups',
                  '17. Education',
                  '19. Cultural Institutions',
                  '20. Online Banking',
                  '21. Online Brokerage and Trading',
                  '22. Games',
                  '23. Government',
                  '24. Military',
                  '25. Political/Advocacy Groups',
                  '26. Health',
                  '27. Information Technology/Computers',
                  '28. Hacking/Proxy Avoidance Systems',
                  '29. Search Engines and Portals',
                  '30. E-Mail',
                  '31. Web Communications',
                  '32. Job Search',
                  '33. News and Media',
                  '34. Personals and Dating',
                  '35. Usenet News Groups',
                  '36. Reference',
                  '37. Religion',
                  '38. Shopping',
                  '39. Internet Auctions',
                  '40. Real Estate',
                  '41. Society and Lifestyle',
                  '43. Restaurants and Dining',
                  '44. Sports/Recreation',
                  '45. Travel',
                  '46. Vehicles',
                  '47. Humor/Jokes',
                  '48. Multimedia',
                  '49. Freeware/Software Downloads',
                  '50. Pay to Surf Sites',
                  '53. Kid Friendly',
                  '54. Advertisement',
                  '55. Web Hosting',
                  '56. Other',
                  '57. Internet Watch Foundation CAIC',
                  '58. Social Networking',
                  '59. Malware',
                  '60. Radicalization and Extremism',
                  '64. Not Rated'
                                                    ]
DEFAULT_TIME_ZONE = ["pacific-time",
                                  "eniwetok,kwajalein", "midway-island,samoa", "hawaii",
                                  "marquesas-islands", "alaska", "pitcairn-islands",
                                  "mexico-tijuana", "arizona", "mountain-time",
                                  "mexico-mazatlan", "central-time", "honduras-tegucigalpa",
                                  "mexico-city", "bogota,indiana-east,lima,quito",
                                  "eastern-time", "caracas", "atlantic-time",
                                  "la-paz", "newfoundland", "brasilia", "buenos-aires,georgetown",
                                  "mid-atlantic", "noronha", "azores", "cape-verde-islands",
                                  "casablanca,monrovia", "united-kingdom", "europe", "egypt", "finland,romania,turkey,greece",
                                  "israel", "jordan,south-africa", "iraq,syria", "russia-gmt+3", "iran", "armenia,azerbaijan",
                                  "afghanistan", "russia-gmt+5", "pakistan", "india", "bangladesh", "russia-gmt+6", "burma"
                                  ]
print(DEFAULT_TIME_ZONE)
